#include "nsISupports.idl"
#include "nsIClassInfo.idl"
#include "nsIFile.idl"
interface mozIStorageConnection;

[scriptable, uuid(034c0c63-b55e-4022-a291-a542db4ea930)]
interface stylishDataSource : nsIClassInfo
{
	mozIStorageConnection getConnection();
	nsIFile getFile();
};  
