pref("extensions.{503a85e3-84c9-40e5-b98e-98e62085837f}.description", "chrome://stylem/locale/common.properties");
pref("extensions.stylem.wrap_lines", true);
pref("extensions.stylem.install.allowedDomains", "userstyles.org");
pref("extensions.stylem.styleRegistrationEnabled", true);
pref("extensions.stylem.firstRun", 0);
pref("extensions.stylem.dbFile", "");
pref("extensions.stylem.promptOnInstall", true);
pref("extensions.stylem.promptOnClear", true);
pref("extensions.stylem.updatesEnabled", true);
pref("extensions.stylem.editor", 0);
pref("extensions.stylem.editorWindowMode", 0);
pref("extensions.stylem.editorWindowPersist", "{\"screenX\": 100, \"screenY\": 100, \"width\": 800, \"height\": 600, \"windowState\": 3}");
pref("extensions.stylem.buttonStylesDisplay.siteMatching", 'show');
pref("extensions.stylem.buttonStylesDisplay.siteNonMatching", 'hide');
pref("extensions.stylem.buttonStylesDisplay.global", 'submenu');
pref("extensions.stylem.buttonStylesDisplay.app", 'hide');
